Repository eduardconstantin/Regenerator, pull requests merged in 2022-10, with the labels that each got.

#3 Add Readme
  IMG/demo.png
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, good first issue

#5 Added code of conduct file
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#8 moved js logic from html to style.js
  JS/style.js
  index.html
Labels: enhancement, hacktoberfest-accepted

#10 Create LICENSE
  LICENSE
Labels: documentation

#12 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#19 feat: added pull request template
  .github/pull_request_template.md
Labels: documentation, hacktoberfest-accepted

#21 Updated style.js file.
  JS/main.js
  JS/style.js
  index.html
Labels: enhancement, hacktoberfest-accepted

#18 Replaced hand images
  CSS/style.css
  IMG/hleft.png
  IMG/hright.png
Labels: enhancement, hacktoberfest-accepted

#27 added css gradient and rounded corner
  CSS/style.css
Labels: enhancement, hacktoberfest-accepted

#30 Added new Song
  MP3/Starlight-Tale-Soft-Classical-Piano-Music.mp3
  index.html
Labels: enhancement, hacktoberfest-accepted

#33 Fixed Issue: Clean style file
  CSS/audio.css
  CSS/normalize.css
  CSS/style.css
  index.html
Labels: enhancement, hacktoberfest-accepted
